<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VShop.ProductApi.Domain\VShop.ProductApi.Domain.csproj" />
  </ItemGroup>

</Project>
